# Makefile for the focaltech touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_spi.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LC)  +=  focaltech_flash.o
