#
# Makefile for the fingerprint drivers.
#
# Each configuration option enables a list of files

obj-$(CONFIG_FINGERPRINT_CDFINGER)	+= cdfinger/
obj-$(CONFIG_FINGERPRINT_614R)		+= elan/
obj-$(CONFIG_FINGERPRINT_FPC1020)	+= fpc1020/
obj-$(CONFIG_FINGERPRINT_FT9362)	+= ft9362/
obj-$(CONFIG_FINGERPRINT_GF5288)	+= goodix_gf5288/
obj-$(CONFIG_FINGERPRINT_SUNWAVE)	+= sunwave/
