#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)   +=  focaltech_sensor.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH)   +=  focaltech_flash/
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH_TESTS)   +=  focaltech_test/
